build:
  environment: python
  pythonVersion: 3.10.13
services:
  - type: web
    name: my-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app